package com.diop.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.Set;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "dev-movie")
public class Movie {
    @DynamoDBHashKey(attributeName = "movieId")
    @DynamoDBAutoGeneratedKey
    private String movieId;
    private Set<String> characters;
    @DynamoDBIndexHashKey(globalSecondaryIndexName="ratingIndex")
    private String rating;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName="ratingIndex")
    private int releaseDate;
    private String series;

    @DynamoDBHashKey()
    private String title;

}
